name: flutter_loadingindicator
description: show Loading cycle grid indicator and more others , Easy to use without context, Support iOSã€Android and Web
version: 1.0.0
homepage: https://github.com/MostafaMohamedMokhtar/flutter_easyloading

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
